# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://github.com/antonbabenko/pre-commit-terraform for terraform hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
        # since the devcontainer-file is not JSON but "JSONWithComments"
        exclude: .devcontainer/devcontainer.json
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
        args: ["--allow-multiple-documents"]
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: .devcontainer.json|docs
        exclude_types: [csv]
        types: [text]
    -   id: mixed-line-ending
        args: ['--fix=lf']
        types: [text]
        exclude_types: [csv]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        exclude_types: [csv]
        types: [text]
    -   id: name-tests-test
        args: ['--django'] # Argument 'django' checks that test file names start with "test"

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    -   id: nbstripout

-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
    -   id: pycln

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
